apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "kafka-operator.name" . }}-webhook-server-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "kafka-operator.name" . }}"
    chart: "{{ include "kafka-operator.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"