apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zookeeper.fullname" . }}-configmap
data:
  cr.yml: |-
    apiVersion: zookeeper.pravega.io/v1beta1
    kind: ZookeeperCluster
    metadata:
      labels:
        app: "{{ template "zookeeper.fullname" . }}"
        chart: "{{ include "zookeeper.chart" . }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
      name: "{{ .Values.cluster.name }}"
    spec:
      replicas: {{ .Values.cluster.size }}