apiVersion: batch/v1
kind: Job
metadata:
  labels:
      app: "{{ template "zookeeper.fullname" . }}"
      chart: "{{ include "zookeeper.chart" . }}"
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
  name: "{{ .Values.cluster.name }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "zookeeper.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "zookeeper.fullname" . }}-init
        image: "solsson/kafka-initutils@sha256:c98d7fb5e9365eab391a5dcd4230fc6e72caf929c60f29ff091e3b0215124713"
        command: [ "/bin/bash", "-c", "until kubectl get crd -o name | grep -q zookeeperclusters.zookeeper.pravega.io; do echo waiting for crd ; sleep 3 ; done ;kubectl create -f /zookeeper_chart/cr.yml;"]
        volumeMounts:
        - name: config
          mountPath: /zookeeper_chart
      restartPolicy: "OnFailure"
      serviceAccountName: {{ template "zookeeper.fullname" . }}
      volumes:
      - name: config
        configMap: 
          name: {{ template "zookeeper.fullname" . }}-configmap