apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: "{{ template "zookeeper.fullname" . }}"
    chart: "{{ include "zookeeper.chart" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - zookeeperclusters
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: "{{ template "zookeeper.fullname" . }}"
    chart: "{{ include "zookeeper.chart" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
subjects:
- kind: ServiceAccount
  name: {{ template "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "zookeeper.fullname" . }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: "{{ template "zookeeper.fullname" . }}"
    chart: "{{ include "zookeeper.chart" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"